site_name: Client Server Dokumentation

nav:
    - Übersicht: index.md
    - Projekt erstellen: Projekt_erstellen.md
    - Server: Server.md
    - Client: Client.md
    - Aufgaben: Exercise.md

theme: 
    name: material
    palette:
        - scheme: slate
    language: de

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  
plugins:
  - offline